code --install-extension aaron-bond.better-comments
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension ctcuff.font-preview
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-faker
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension expo.vscode-expo-tools
code --install-extension figma.figma-vscode-extension
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension jebbs.plantuml
code --install-extension jock.svg
code --install-extension mathiasfrohlich.kotlin
code --install-extension meganrogge.template-string-converter
code --install-extension million.million-lint
code --install-extension mylesmurphy.prettify-ts
code --install-extension naumovs.color-highlight
code --install-extension orta.vscode-twoslash-queries
code --install-extension pilaton.vscode-npm-lens
code --install-extension pkief.material-icon-theme
code --install-extension plibither8.remove-comments
code --install-extension stxr.iconfont-preview
code --install-extension teabyii.ayu
code --install-extension unifiedjs.vscode-mdx
code --install-extension wayou.vscode-todo-highlight
code --install-extension wmaurer.change-case
code --install-extension xdebug.php-debug
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
